version: '3.7'
services:
  bookapp:
    container_name: bookapp
    build: .
    command: python /bookstore_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore_project
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY==67areid!+4l#7)xs&+j9k7zc#%ctl8tk*)xix38b%m_t(lw(@"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
